# Generated by Django 4.1.5 on 2023-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('busy', models.BooleanField(default=False)),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('start_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
