# Generated by Django 4.1.5 on 2023-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_table_start_time_alter_table_visitor_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='is_available',
            new_name='busy',
        ),
    ]
